application: fanapton
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /Authentication      #app engine does not recognize your actual local directory
  static_dir: Authentication

- url: /.*
  script: main.app


libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest