runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /Authentication      #app engine does not recognize your actual local directory
  static_dir: Authentication

- url: /Static
  static_dir: Static

- url: /Mobile/.*
  script: Mobile.main.app

- url: /.*
  script: fanapton.app

libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest
- name: ssl
  version: latest